export enum Permission {
  READ_ORDERS = 'READ_ORDERS',
  WRITE_ORDERS = 'WRITE_ORDERS',
  MANAGE_MENU = 'MANAGE_MENU',
  MANAGE_STAFF = 'MANAGE_STAFF',
  READ_KITCHEN_TICKETS = 'READ_KITCHEN_TICKETS',
  WRITE_KITCHEN_TICKETS = 'WRITE_KITCHEN_TICKETS',
  MANAGE_IDENTITY = 'MANAGE_IDENTITY'
}
